contact_links:
  - name: 🗨 Discussions
    url: https://github.com/d4n3436/revanced-patches-android5/discussions
    about: This can be used for questions, suggestions, supports, announcements, etc. Search for or start a new discussion!
