contact_links:
  - name: 💊 ReVanced Manager issue?
    url: https://github.com/kitadai31/revanced-manager-android6-7/issues
    about: Do you have an issue with Manager? Please report it in Manager repo, not here.
  - name: 🗨 Discussions
    url: https://github.com/kitadai31/revanced-patches-android6-7/discussions
    about: This can be used for questions, suggestions, supports, announcements, etc. Search for or start a new discussion!
